// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Article } from '../../../article/content-types/article/article';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Article_Plain } from '../../../article/content-types/article/article';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ArticleEco {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    slug?: string;
    cover?: { data: Media };
    author?: { data: Article };
    categories: { data: Article[] };
    blocks: any;
    content: string;
    og: { data: Media };
    tags: { data: Article[] };
  };
}
export interface ArticleEco_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: Media_Plain;
  author?: Article_Plain;
  categories: Article_Plain[];
  blocks: any;
  content: string;
  og: Media_Plain;
  tags: Article_Plain[];
}

export interface ArticleEco_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: number;
  author?: number;
  categories: number[];
  blocks: any;
  content: string;
  og: number;
  tags: number[];
}

export interface ArticleEco_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  slug?: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: AdminPanelRelationPropertyModification<Article_Plain>;
  categories: AdminPanelRelationPropertyModification<Article_Plain>;
  blocks: any;
  content: string;
  og: AdminPanelRelationPropertyModification<Media_Plain>;
  tags: AdminPanelRelationPropertyModification<Article_Plain>;
}
