// Interface automatically generated by schemas-to-ts

export interface Tag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    tag?: string;
    locale: string;
    localizations?: { data: Tag[] };
  };
}
export interface Tag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag?: string;
  locale: string;
  localizations?: Tag_Plain[];
}

export interface Tag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag?: string;
  locale: string;
  localizations?: Tag[];
}

export interface Tag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag?: string;
  locale: string;
  localizations?: Tag[];
}
