// Interface automatically generated by schemas-to-ts

export interface CareerRaydiancloud {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    content: string;
    location: string;
    employmentType: string;
    locationType: string;
    department: string;
    briefDetails: any;
    slug: string;
    locale: string;
    localizations?: { data: CareerRaydiancloud[] };
  };
}
export interface CareerRaydiancloud_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  content: string;
  location: string;
  employmentType: string;
  locationType: string;
  department: string;
  briefDetails: any;
  slug: string;
  locale: string;
  localizations?: CareerRaydiancloud_Plain[];
}

export interface CareerRaydiancloud_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  content: string;
  location: string;
  employmentType: string;
  locationType: string;
  department: string;
  briefDetails: any;
  slug: string;
  locale: string;
  localizations?: CareerRaydiancloud[];
}

export interface CareerRaydiancloud_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  content: string;
  location: string;
  employmentType: string;
  locationType: string;
  department: string;
  briefDetails: any;
  slug: string;
  locale: string;
  localizations?: CareerRaydiancloud[];
}
