// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Article } from '../../../article/content-types/article/article';
import { Blog } from '../../../blog/content-types/blog/blog';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Article_Plain } from '../../../article/content-types/article/article';
import { Blog_Plain } from '../../../blog/content-types/blog/blog';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Author {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    avatar?: { data: Media };
    email?: string;
    articles: { data: Article[] };
    blogs: { data: Blog[] };
  };
}
export interface Author_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: Media_Plain;
  email?: string;
  articles: Article_Plain[];
  blogs: Blog_Plain[];
}

export interface Author_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: number;
  email?: string;
  articles: number[];
  blogs: number[];
}

export interface Author_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  avatar?: AdminPanelRelationPropertyModification<Media_Plain>;
  email?: string;
  articles: AdminPanelRelationPropertyModification<Article_Plain>;
  blogs: AdminPanelRelationPropertyModification<Blog_Plain>;
}
