// Interface automatically generated by schemas-to-ts

import { ArticleFtk } from '../../../article-ftk/content-types/article-ftk/article-ftk';
import { ArticleFtk_Plain } from '../../../article-ftk/content-types/article-ftk/article-ftk';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface TagFtk {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    tag: string;
    articles?: { data: ArticleFtk[] };
    locale: string;
    localizations?: { data: TagFtk[] };
  };
}
export interface TagFtk_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: ArticleFtk_Plain[];
  locale: string;
  localizations?: TagFtk_Plain[];
}

export interface TagFtk_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: number[];
  locale: string;
  localizations?: TagFtk[];
}

export interface TagFtk_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: AdminPanelRelationPropertyModification<ArticleFtk_Plain>;
  locale: string;
  localizations?: TagFtk[];
}
