// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Author } from '../../../author/content-types/author/author';
import { Category } from '../../../category/content-types/category/category';
import { Tag } from '../../../tag/content-types/tag/tag';
import { ArticleEco } from '../../../article-eco/content-types/article-eco/article-eco';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Author_Plain } from '../../../author/content-types/author/author';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { ArticleEco_Plain } from '../../../article-eco/content-types/article-eco/article-eco';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    slug?: string;
    cover: { data: Media };
    author?: { data: Author };
    categories: { data: Category[] };
    blocks?: any;
    content: string;
    og: { data: Media };
    tags: { data: Tag[] };
    article_ecos: { data: ArticleEco[] };
    locale: string;
    localizations?: { data: Article[] };
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  cover: Media_Plain;
  author?: Author_Plain;
  categories: Category_Plain[];
  blocks?: any;
  content: string;
  og: Media_Plain;
  tags: Tag_Plain[];
  article_ecos: ArticleEco_Plain[];
  locale: string;
  localizations?: Article_Plain[];
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  cover: number;
  author?: number;
  categories: number[];
  blocks?: any;
  content: string;
  og: number;
  tags: number[];
  article_ecos: number[];
  locale: string;
  localizations?: Article[];
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  cover: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: AdminPanelRelationPropertyModification<Author_Plain>;
  categories: AdminPanelRelationPropertyModification<Category_Plain>;
  blocks?: any;
  content: string;
  og: AdminPanelRelationPropertyModification<Media_Plain>;
  tags: AdminPanelRelationPropertyModification<Tag_Plain>;
  article_ecos: AdminPanelRelationPropertyModification<ArticleEco_Plain>;
  locale: string;
  localizations?: Article[];
}
