// Interface automatically generated by schemas-to-ts

import { Options } from '../../../../components/question/interfaces/Options';
import { Options_Plain } from '../../../../components/question/interfaces/Options';
import { Options_NoRelations } from '../../../../components/question/interfaces/Options';

export interface QuestionType {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    text?: string;
    yesNo?: boolean;
    multipleOptions: Options[];
    locale: string;
    localizations?: { data: QuestionType[] };
  };
}
export interface QuestionType_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  yesNo?: boolean;
  multipleOptions: Options_Plain[];
  locale: string;
  localizations?: QuestionType_Plain[];
}

export interface QuestionType_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  yesNo?: boolean;
  multipleOptions: Options_NoRelations[];
  locale: string;
  localizations?: QuestionType[];
}

export interface QuestionType_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  text?: string;
  yesNo?: boolean;
  multipleOptions: Options_Plain[];
  locale: string;
  localizations?: QuestionType[];
}
