// Interface automatically generated by schemas-to-ts

export interface QuestionCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    locale: string;
    localizations?: { data: QuestionCategory[] };
  };
}
export interface QuestionCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  locale: string;
  localizations?: QuestionCategory_Plain[];
}

export interface QuestionCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  locale: string;
  localizations?: QuestionCategory[];
}

export interface QuestionCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  locale: string;
  localizations?: QuestionCategory[];
}
