// Interface automatically generated by schemas-to-ts

import { ArticleRaydiancloud } from '../../../article-raydiancloud/content-types/article-raydiancloud/article-raydiancloud';
import { ArticleRaydiancloud_Plain } from '../../../article-raydiancloud/content-types/article-raydiancloud/article-raydiancloud';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface TagRaydiancloud {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    tag: string;
    articles?: { data: ArticleRaydiancloud[] };
    locale: string;
    localizations?: { data: TagRaydiancloud[] };
  };
}
export interface TagRaydiancloud_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: ArticleRaydiancloud_Plain[];
  locale: string;
  localizations?: TagRaydiancloud_Plain[];
}

export interface TagRaydiancloud_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: number[];
  locale: string;
  localizations?: TagRaydiancloud[];
}

export interface TagRaydiancloud_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  tag: string;
  articles?: AdminPanelRelationPropertyModification<ArticleRaydiancloud_Plain>;
  locale: string;
  localizations?: TagRaydiancloud[];
}
