// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Article } from '../../../article/content-types/article/article';
import { TagRaydiancloud } from '../../../tag-raydiancloud/content-types/tag-raydiancloud/tag-raydiancloud';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Article_Plain } from '../../../article/content-types/article/article';
import { TagRaydiancloud_Plain } from '../../../tag-raydiancloud/content-types/tag-raydiancloud/tag-raydiancloud';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ArticleRaydiancloud {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    slug: string;
    cover: { data: Media };
    author?: string;
    categories: { data: Article[] };
    content: string;
    og: { data: Media };
    tags: { data: Article[] };
    raydiancloud_tags?: { data: TagRaydiancloud[] };
    publishDate?: Date;
    locale: string;
    localizations?: { data: ArticleRaydiancloud[] };
  };
}
export interface ArticleRaydiancloud_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: Media_Plain;
  author?: string;
  categories: Article_Plain[];
  content: string;
  og: Media_Plain;
  tags: Article_Plain[];
  raydiancloud_tags?: TagRaydiancloud_Plain[];
  publishDate?: Date;
  locale: string;
  localizations?: ArticleRaydiancloud_Plain[];
}

export interface ArticleRaydiancloud_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: number;
  author?: string;
  categories: number[];
  content: string;
  og: number;
  tags: number[];
  raydiancloud_tags?: number[];
  publishDate?: Date;
  locale: string;
  localizations?: ArticleRaydiancloud[];
}

export interface ArticleRaydiancloud_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: string;
  categories: AdminPanelRelationPropertyModification<Article_Plain>;
  content: string;
  og: AdminPanelRelationPropertyModification<Media_Plain>;
  tags: AdminPanelRelationPropertyModification<Article_Plain>;
  raydiancloud_tags?: AdminPanelRelationPropertyModification<TagRaydiancloud_Plain>;
  publishDate?: Date;
  locale: string;
  localizations?: ArticleRaydiancloud[];
}
