// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Article } from '../../../article/content-types/article/article';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Article_Plain } from '../../../article/content-types/article/article';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ArticleFtk {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: string;
    slug: string;
    cover: { data: Media };
    author?: { data: Article };
    categories: { data: Article[] };
    content: string;
    og: { data: Media };
    tags: { data: Article[] };
    publishDate?: Date;
    locale: string;
    localizations?: { data: ArticleFtk[] };
  };
}
export interface ArticleFtk_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: Media_Plain;
  author?: Article_Plain;
  categories: Article_Plain[];
  content: string;
  og: Media_Plain;
  tags: Article_Plain[];
  publishDate?: Date;
  locale: string;
  localizations?: ArticleFtk_Plain[];
}

export interface ArticleFtk_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: number;
  author?: number;
  categories: number[];
  content: string;
  og: number;
  tags: number[];
  publishDate?: Date;
  locale: string;
  localizations?: ArticleFtk[];
}

export interface ArticleFtk_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: string;
  slug: string;
  cover: AdminPanelRelationPropertyModification<Media_Plain>;
  author?: AdminPanelRelationPropertyModification<Article_Plain>;
  categories: AdminPanelRelationPropertyModification<Article_Plain>;
  content: string;
  og: AdminPanelRelationPropertyModification<Media_Plain>;
  tags: AdminPanelRelationPropertyModification<Article_Plain>;
  publishDate?: Date;
  locale: string;
  localizations?: ArticleFtk[];
}
